spring:
  application:
    name: dispatch-service
  datasource:
    url: jdbc:sqlite:/dbsqlite/dispatch.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC

dubbo:
  registry:
    address: multicast://224.5.6.7:1234
  protocol:
    name: dubbo
    port: 28081
    host: 127.0.0.1